export interface Teacher {
  id: string;
  name: string;
  nip: string;
  phone: string;
  email: string;
}

export interface Subject {
  id: string;
  name: string;
  code: string;
  totalSessions: number;
}

export interface ClassGroup {
  id: string;
  name: string;
  gradeLevel: number;
  section: string;
}

export interface Room {
  id: string;
  name: string;
  code: string;
  capacity: number;
}

export interface TimeSlot {
  id: string;
  dayOfWeek: number;
  startTime: string;
  endTime: string;
  type: 'teaching' | 'break';
}

export interface TeacherAvailability {
  id: string;
  teacherId: string;
  dayOfWeek: number;
  startTime: string;
  endTime: string;
}

export interface TeachingAssignment {
  id: string;
  teacherId: string;
  subjectId: string;
  classId: string;
  sessionsPerWeek: number;
}

export interface ScheduleEntry {
  id: string;
  teacherId: string;
  subjectId: string;
  classId: string;
  roomId: string;
  timeSlotId: string;
  isAutoGenerated: boolean;
}

export interface ScheduleDisplay extends ScheduleEntry {
  teacherName: string;
  subjectName: string;
  className: string;
  roomName: string;
  subjectColor: string;
}

export interface AcademicYear {
  id: string;
  tahunAjaran: string;
  semester: 'ganjil' | 'genap';
}

export const DAYS_5 = ['Senin', 'Selasa', 'Rabu', 'Kamis', "Jum'at"];
export const DAYS_6 = ['Senin', 'Selasa', 'Rabu', 'Kamis', "Jum'at", 'Sabtu'];
export const DAYS = DAYS_6;

export function getDays(schoolType: string): string[] {
  return schoolType === 'swasta' ? DAYS_6 : DAYS_5;
}

export function getMaxDay(schoolType: string): number {
  return schoolType === 'swasta' ? 6 : 5;
}

export const SUBJECT_COLORS = [
  '#4f46e5', '#0891b2', '#059669', '#d97706',
  '#dc2626', '#7c3aed', '#db2777', '#2563eb',
  '#ca8a04', '#16a34a', '#9333ea', '#ea580c',
];
