import { Router } from 'express';
import { db } from '../db/index';
import { schedules } from '../db/schema/schedules';
import { eq } from 'drizzle-orm';
import { v4 as uuid } from 'uuid';

const router = Router();

router.get('/', async (_req, res) => {
  const data = await db.select().from(schedules);
  res.json(data);
});

router.post('/', async (req, res) => {
  const { id, teacherId, subjectId, classId, roomId, timeSlotId, isAutoGenerated } = req.body;
  const data = {
    id: id || uuid(), teacherId, subjectId, classId, roomId, timeSlotId,
    isAutoGenerated: isAutoGenerated ? 1 : 0,
  };
  await db.insert(schedules).values(data);
  res.json({ ...data, isAutoGenerated: !!data.isAutoGenerated });
});

router.put('/:id', async (req, res) => {
  const { teacherId, subjectId, classId, roomId, timeSlotId, isAutoGenerated } = req.body;
  await db.update(schedules).set({
    teacherId, subjectId, classId, roomId, timeSlotId,
    isAutoGenerated: isAutoGenerated ? 1 : 0,
  }).where(eq(schedules.id, req.params.id));
  res.json({ id: req.params.id, teacherId, subjectId, classId, roomId, timeSlotId, isAutoGenerated });
});

router.delete('/:id', async (req, res) => {
  await db.delete(schedules).where(eq(schedules.id, req.params.id));
  res.json({ ok: true });
});

router.delete('/', async (_req, res) => {
  await db.delete(schedules);
  res.json({ ok: true });
});

export default router;
