import { db } from '../db/index';
import { schedules } from '../db/schema/schedules';
import { timeSlots } from '../db/schema/timeSlots';
import { rooms } from '../db/schema/rooms';
import { assignments } from '../db/schema/assignments';
import { availabilities } from '../db/schema/availabilities';
import { settings } from '../db/schema/settings';
import { eq } from 'drizzle-orm';
import { v4 as uuid } from 'uuid';

function timeToMin(t: string): number {
  const [h, m] = t.split(':').map(Number);
  return h * 60 + m;
}

async function getMaxDayOfWeek(): Promise<number> {
  const row = await db.select().from(settings).where(eq(settings.key, 'schoolType')).limit(1);
  const schoolType = row.length > 0 ? row[0].value : 'negeri';
  return schoolType === 'swasta' ? 6 : 5;
}

export async function generateSchedule(): Promise<{ schedules: Record<string, unknown>[]; conflicts: string[] }> {
  const maxDay = await getMaxDayOfWeek();
  const allSlots = await db.select().from(timeSlots);
  const allRooms = await db.select().from(rooms);
  const allAssignments = await db.select().from(assignments);
  const allAvailabilities = await db.select().from(availabilities);

  const teachingSlotsByDay: Record<number, typeof allSlots> = {};
  for (const ts of allSlots) {
    if (ts.type !== 'teaching') continue;
    if (!teachingSlotsByDay[ts.dayOfWeek]) teachingSlotsByDay[ts.dayOfWeek] = [];
    teachingSlotsByDay[ts.dayOfWeek].push(ts);
  }
  for (const day of Object.keys(teachingSlotsByDay)) {
    teachingSlotsByDay[Number(day)].sort((a, b) => timeToMin(a.startTime) - timeToMin(b.startTime));
  }

  const usedTeacherSlots = new Set<string>();
  const usedClassSlots = new Set<string>();
  const usedRoomSlots = new Set<string>();

  const sorted = [...allAssignments].sort((a, b) => {
    const aAvail = allAvailabilities.filter((av) => av.teacherId === a.teacherId).length;
    const bAvail = allAvailabilities.filter((av) => av.teacherId === b.teacherId).length;
    return aAvail - bAvail;
  });

  const result: Record<string, unknown>[] = [];
  const conflicts: string[] = [];

  for (const assignment of sorted) {
    const needed = assignment.sessionsPerWeek;
    let placed = 0;

    for (let day = 1; day <= maxDay && placed < needed; day++) {
      const daySlots = teachingSlotsByDay[day] || [];
      let i = 0;

      while (i < daySlots.length && placed < needed) {
        const remaining = needed - placed;
        const consecutive: typeof allSlots = [];

        for (let j = i; j < daySlots.length && consecutive.length < remaining; j++) {
          const prev = consecutive[consecutive.length - 1];
          if (prev && prev.endTime !== daySlots[j].startTime) break;
          consecutive.push(daySlots[j]);
        }

        if (consecutive.length < remaining) { i++; continue; }

        const allFree = consecutive.every((slot) => {
          const tKey = `${slot.dayOfWeek}-${slot.id}-${assignment.teacherId}`;
          const cKey = `${slot.dayOfWeek}-${slot.id}-${assignment.classId}`;
          const roomFree = allRooms.some((r) => {
            const rKey = `${slot.dayOfWeek}-${slot.id}-${r.id}`;
            return !usedRoomSlots.has(rKey);
          });
          return !usedTeacherSlots.has(tKey) && !usedClassSlots.has(cKey) && roomFree;
        });

        if (!allFree) { i++; continue; }

        let ok = true;
        for (let k = 0; k < remaining; k++) {
          const slot = consecutive[k];
          const availableRooms = allRooms.filter((r) => {
            const rKey = `${slot.dayOfWeek}-${slot.id}-${r.id}`;
            return !usedRoomSlots.has(rKey);
          });
          if (availableRooms.length === 0) { ok = false; break; }

          const room = availableRooms[0];
          const tKey = `${slot.dayOfWeek}-${slot.id}-${assignment.teacherId}`;
          const cKey = `${slot.dayOfWeek}-${slot.id}-${assignment.classId}`;
          const rKey = `${slot.dayOfWeek}-${slot.id}-${room.id}`;

          usedTeacherSlots.add(tKey);
          usedClassSlots.add(cKey);
          usedRoomSlots.add(rKey);

          result.push({
            id: uuid(),
            teacherId: assignment.teacherId,
            subjectId: assignment.subjectId,
            classId: assignment.classId,
            roomId: room.id,
            timeSlotId: slot.id,
            isAutoGenerated: true,
          });
        }

        if (ok) placed += remaining;
        i++;
      }
    }

    if (placed < needed) {
      conflicts.push(`Pengajaran ${assignment.id}: hanya ${placed}/${needed} sesi terjadwal`);
    }
  }

  await db.delete(schedules);
  if (result.length > 0) {
    const values = result.map((r) => ({
      id: r.id as string,
      teacherId: r.teacherId as string,
      subjectId: r.subjectId as string,
      classId: r.classId as string,
      roomId: r.roomId as string,
      timeSlotId: r.timeSlotId as string,
      isAutoGenerated: 1,
    }));
    await db.insert(schedules).values(values);
  }

  return { schedules: result, conflicts };
}
